# Generated by Django 5.1.6 on 2025-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('author', models.CharField(blank=True, max_length=80, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
